"""patient saved places

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 22:22:32.197416
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patient_profiles", sa.Column("home_label", sa.String(length=80), nullable=True))
    op.add_column("patient_profiles", sa.Column("home_latitude", sa.Double(), nullable=True))
    op.add_column("patient_profiles", sa.Column("home_longitude", sa.Double(), nullable=True))
    op.add_column("patient_profiles", sa.Column("work_label", sa.String(length=80), nullable=True))
    op.add_column("patient_profiles", sa.Column("work_latitude", sa.Double(), nullable=True))
    op.add_column("patient_profiles", sa.Column("work_longitude", sa.Double(), nullable=True))
    op.create_check_constraint(
        "home_pair",
        "patient_profiles",
        "(home_latitude IS NULL) = (home_longitude IS NULL)",
    )
    op.create_check_constraint(
        "work_pair",
        "patient_profiles",
        "(work_latitude IS NULL) = (work_longitude IS NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_patient_profiles_work_pair"), "patient_profiles", type_="check")
    op.drop_constraint(op.f("ck_patient_profiles_home_pair"), "patient_profiles", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patient_profiles", "work_longitude")
    op.drop_column("patient_profiles", "work_latitude")
    op.drop_column("patient_profiles", "work_label")
    op.drop_column("patient_profiles", "home_longitude")
    op.drop_column("patient_profiles", "home_latitude")
    op.drop_column("patient_profiles", "home_label")
    # ### end Alembic commands ###
