"""environment: stations, aq observations, weather, ingestion runs

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 23:47:32.603165
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_valid", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("duplicates_dropped", sa.Integer(), nullable=False),
        sa.Column("rejection_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_station_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("is_reference_monitor", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
        sa.UniqueConstraint("source", "source_station_id", name=op.f("uq_stations_source")),
    )
    op.create_table(
        "air_quality_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("station_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column(
            "pollutant",
            sa.Enum(
                "pm25",
                "pm10",
                "no2",
                "o3",
                "so2",
                "co",
                name="pollutant",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("concentration", sa.Double(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("raw_value", sa.Double(), nullable=False),
        sa.Column("raw_unit", sa.String(length=16), nullable=False),
        sa.Column("coverage_pct", sa.Double(), nullable=True),
        sa.Column(
            "quality_flag",
            sa.Enum(
                "valid",
                "low_coverage",
                "provider_flagged",
                "implausible",
                name="quality_flag",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ingestion_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_air_quality_observations_ingestion_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_air_quality_observations_station_id_stations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_air_quality_observations")),
        sa.UniqueConstraint(
            "source", "station_id", "pollutant", "timestamp", name="uq_aq_obs_identity"
        ),
    )
    op.create_index(
        "ix_aq_obs_pollutant_timestamp",
        "air_quality_observations",
        ["pollutant", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_aq_obs_station_pollutant_timestamp",
        "air_quality_observations",
        ["station_id", "pollutant", "timestamp"],
        unique=False,
    )
    op.create_table(
        "weather_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("temperature", sa.Double(), nullable=True),
        sa.Column("relative_humidity", sa.Double(), nullable=True),
        sa.Column("precipitation", sa.Double(), nullable=True),
        sa.Column("wind_speed", sa.Double(), nullable=True),
        sa.Column("wind_direction", sa.Double(), nullable=True),
        sa.Column("pressure", sa.Double(), nullable=True),
        sa.Column("ingestion_run_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_weather_observations_ingestion_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_observations")),
        sa.UniqueConstraint(
            "source",
            "kind",
            "latitude",
            "longitude",
            "timestamp",
            "issued_at",
            name="uq_weather_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_weather_observations_timestamp", "weather_observations", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_weather_observations_timestamp", table_name="weather_observations")
    op.drop_table("weather_observations")
    op.drop_index("ix_aq_obs_station_pollutant_timestamp", table_name="air_quality_observations")
    op.drop_index("ix_aq_obs_pollutant_timestamp", table_name="air_quality_observations")
    op.drop_table("air_quality_observations")
    op.drop_table("stations")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
