"""locations

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 00:25:39.795247
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("accuracy_m", sa.Double(), nullable=True),
        sa.Column(
            "activity_context",
            sa.Enum(
                "outdoor",
                "indoor_home",
                "indoor_other",
                "in_transit",
                "unknown",
                name="micro_environment",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_locations_patient_id_patient_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("patient_id", "timestamp", name="uq_locations_patient_timestamp"),
    )
    op.create_index(
        "ix_locations_patient_id_timestamp", "locations", ["patient_id", "timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_locations_patient_id_timestamp", table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
